window.SCFL_CORE_NODE_DEFINITIONS = {
  material: {
    type: 'material',
    label: 'Material',
    category: 'Supply Chain',
    inputs: [],
    outputs: ['material', 'information'],
    fields: [
      { key: 'name', label: 'Name', type: 'string', required: true, defaultValue: (i) => `Material ${i}` },
    ],
  },
  supplier: {
    type: 'supplier',
    label: 'Supplier',
    category: 'Supply Chain',
    inputs: [],
    outputs: ['material', 'information'],
    fields: [
      { key: 'name', label: 'Name', type: 'string', required: true, defaultValue: (i) => `Supplier ${i}` },
      { key: 'deliveryFrequencyDays', label: 'Delivery frequency (days)', type: 'int', required: true, min: 1, step: 1, defaultValue: 3 },
      { key: 'deliveryQuantity', label: 'Delivery quantity', type: 'int', required: true, min: 1, step: 1, defaultValue: 120 },
      { key: 'leadTimeDays', label: 'Lead time (days)', type: 'int', required: true, min: 0, step: 1, defaultValue: 1 },
      { key: 'initialInventory', label: 'Initial inventory (optional)', type: 'int', required: false, min: 0, step: 1, defaultValue: null },
    ],
  },
  warehouse: {
    type: 'warehouse',
    label: 'Warehouse',
    category: 'Supply Chain',
    inputs: ['material', 'information'],
    outputs: ['material', 'information'],
    fields: [
      { key: 'name', label: 'Name', type: 'string', required: true, defaultValue: (i) => `Warehouse ${i}` },
      { key: 'preparationTimeDays', label: 'Preparation time (days)', type: 'int', required: true, min: 0, step: 1, defaultValue: 1 },
      { key: 'preparationCapacityPerDay', label: 'Preparation capacity / day (optional)', type: 'int', required: false, min: 1, step: 1, defaultValue: null },
      { key: 'deliveryToPlantDays', label: 'Delivery to plant (days)', type: 'int', required: true, min: 0, step: 1, defaultValue: 2 },
      { key: 'storageCapacity', label: 'Storage capacity', type: 'int', required: true, min: 1, step: 1, defaultValue: 600 },
      { key: 'initialInventory', label: 'Initial inventory', type: 'int', required: true, min: 0, step: 1, defaultValue: 120 },
      { key: 'reorderPoint', label: 'Reorder point (optional)', type: 'int', required: false, min: 0, step: 1, defaultValue: null },
    ],
  },
  plant: {
    type: 'plant',
    label: 'Plant',
    category: 'Supply Chain',
    inputs: ['material', 'information'],
    outputs: ['material', 'information'],
    fields: [
      { key: 'name', label: 'Name', type: 'string', required: true, defaultValue: (i) => `Plant ${i}` },
      { key: 'consumptionRatePerDay', label: 'Consumption rate / day', type: 'int', required: true, min: 0, step: 1, defaultValue: 20 },
      { key: 'initialInventory', label: 'Initial inventory', type: 'int', required: true, min: 0, step: 1, defaultValue: 100 },
      { key: 'safetyStock', label: 'Safety stock (optional)', type: 'int', required: false, min: 0, step: 1, defaultValue: null },
      { key: 'selectedMaterialIds', label: 'Site materials', type: 'multiselect_materials', required: false, defaultValue: [] },
    ],
  },
  analytics: {
    type: 'analytics',
    label: 'Analytics',
    category: 'Analytics',
    inputs: ['information'],
    outputs: ['information'],
    fields: [
      { key: 'name', label: 'Name', type: 'string', required: true, defaultValue: (i) => `Analytics ${i}` },
      { key: 'sourceNodeId', label: 'Source node', type: 'select_analytics_source', required: false, defaultValue: null },
      {
        key: 'metric',
        label: 'Metric',
        type: 'select',
        required: true,
        options: [
          { value: 'stockout_count', label: 'Stockout events' },
          { value: 'avg_plant_inventory', label: 'Avg plant inventory' },
          { value: 'warehouse_utilization', label: 'Warehouse utilization %' },
          { value: 'on_time_rate', label: 'On-time delivery %' },
          { value: 'avg_queue_time', label: 'Avg warehouse queue time (days)' },
          { value: 'avg_fulfillment_delay', label: 'Avg fulfillment delay (days)' },
          { value: 'total_shipped', label: 'Total shipped volume' },
          { value: 'shipments_today', label: 'Shipments today' },
          { value: 'node_inventory', label: 'Connected node inventory' },
          { value: 'node_shipped', label: 'Connected node shipped' },
          { value: 'node_stockouts', label: 'Connected node stockouts' },
        ],
        defaultValue: 'stockout_count',
      },
    ],
  },
};
